export const LOAD_CUSTOMERS_REQUEST = 'customer:LOAD_CUSTOMERS_REQUEST';
export const LOAD_CUSTOMERS_SUCCESS = 'customer:LOAD_CUSTOMERS_SUCCESS';
export const LOAD_CUSTOMERS_FAILURE = 'customer:LOAD_CUSTOMERS_FAILURE';

export const SAVE_CUSTOMER__REQUEST = 'customer:SAVE_CUSTOMER__REQUEST';
export const SAVE_CUSTOMER__SUCCESS = 'customer:SAVE_CUSTOMER__SUCCESS';
export const SAVE_CUSTOMER__FAILURE = 'customer:SAVE_CUSTOMER__FAILURE';

export const SELECT_CUSTOMER_TO_UPDATE = 'customer:SELECT_CUSTOMER_TO_UPDATE';
export const UPDATE_CUSTOMER_REQUEST = 'customer:UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'customer:UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAILURE = 'customer:UPDATE_CUSTOMER_FAILURE';

export const DELETE_CUSTOMER_REQUEST = 'customer:DELETE_CUSTOMER_REQUEST';
export const DELETE_CUSTOMER_SUCCESS = 'customer:DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAILURE = 'customer:DELETE_CUSTOMER_FAILURE';
